@OOLanches.API_HostAddress = http://localhost:5033
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJqb2FvLnNpbHZhQGV4YW1wbGUuY29tIiwiZXhwIjoxNzM2NjQ3ODE5LCJpc3MiOiJodHRwczovL2xvY2FsaG9zdDo3MDY2LyIsImF1ZCI6Imh0dHBzOi8vbG9jYWxob3N0OjcwNjYvIn0.HG1kFupNruR0ygqVizzx5fXYB605ZdIw6I2nbhWDnDM

### Verificar produtos no carrinho
GET {{OOLanches.API_HostAddress}}/api/ItensCarrinhoCompra/1
Authorization: Bearer {{Token}}
Content-Type: application/json;

### Inserir Produto no Carrinho
POST {{OOLanches.API_HostAddress}}/api/ItensCarrinhoCompra
Authorization: Bearer {{Token}}
Accept: application/json
Content-Type: application/json

{
  "precoUnitario": 5.3,
  "quantidade": 3,
  "clienteId": 1,
  "produtoId": 2
}

### Aumentar a quantidade do item no carrinho
PUT {{OOLanches.API_HostAddress}}/api/ItensCarrinhoCompra?produtoId=1&acao=aumentar
Authorization: Bearer {{Token}}
Content-Type: application/json
Accept: application/json

{}

### Diminuir a quantidade do item no carrinho
PUT {{OOLanches.API_HostAddress}}/api/ItensCarrinhoCompra?produtoId=1&acao=diminuir
Authorization: Bearer {{Token}}
Content-Type: application/json
Accept: application/json

{}

### Deletar o item do carrinho
PUT {{OOLanches.API_HostAddress}}/api/ItensCarrinhoCompra?produtoId=2&acao=deletar
Authorization: Bearer {{Token}}
Content-Type: application/json
Accept: application/json

{}